CREATE TABLE dbo.TUsuarioPreferencia(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_Usuario INT NOT NULL,
	ID_Programa VARCHAR(10) NOT NULL,
	DS_Tipo VARCHAR(50) NOT NULL,
	NM_Objeto VARCHAR(50) NULL,
	OB_Valor VARBINARY(MAX) NULL
);